version: '3.8'

services:
  user_api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/usr/src/user_api
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fastapi_test_task
    ports:
      - 5432:5432

volumes:
  postgres_data: